### ISSUE TITLE
Setting OAuth Web

### ISSUE THREAD

**Issue by laresbernardo** [dkulp2/Google-Sign-In#2]
Hi! Thanks for your code. I think it will be quite useful for what I'm working with. But I've been having some issue at the last step. I'm running it from RStudio in a MatrixDS instance and added my link to the authorized Javascripts. 

The pop-up works and everything seems just fine but when I enter with my account, nothing happens. I think it's something in Google's settings but I'm not sure what. What I think is that the redirect link is not set properly but I guess I don't know how.

<img width="960" alt="Captura de Pantalla 2019-09-11 a la(s) 12 02 37 p  m" src="https://user-images.githubusercontent.com/25909073/64709147-28692480-d48c-11e9-9cb0-53d2ae2f2781.png">

I'm sharing a screenshot on my settings to see if you detect something here. Thanks for your help @dkulp2 👍 

<img width="627" alt="Captura de Pantalla 2019-09-11 a la(s) 12 01 24 p  m" src="https://user-images.githubusercontent.com/25909073/64709046-f6f05900-d48b-11e9-8ca4-ee9b1816bf0d.png">

**Comment by dkulp2** [comment]
Does this work for localhost? That's a good place to start before worrying about cloud hosting.

My memory is not good, but all my redirect URLs are identical to the origins URLs. I think that's what you want to do - including ports. That way after authentication your applications gets the user data.

Regarding cloud hosting, I always create DNS entries in my own domain that point to cloud instances and use those names in the OAuth settings.

**Comment by laresbernardo** [comment]
Thanks for your reply @dkulp2 
In localhost I get the same response: pop-up, login, it closes and nothing else happens. It must be the redirect part. I actually am using the same URL in both places as you mention for localhost.
Could you be so kind as to share with me an example of how should the Google Project URLs should be set? Maybe with localhost AND with a cloud hosting example? 
Thanks again, really appreciate it!

**Comment by dkulp2** [comment]
Here's a screenshot of the "client ID for Web application" page used for this repo's demo code. I suggest trying to reproduce this by creating your own "OAuth 2.0 Client ID" and replace the ID in the code with yours. If it works properly, then you can add more host names. 
<img width="762" alt="oauth" src="https://user-images.githubusercontent.com/1669196/65140994-bfc6fe00-d9dd-11e9-8ace-d898ad6fd019.png">

**Comment by laresbernardo** [comment]
Awesome. I did exactly that, same port same everything and worked locally. Thanks!

Now, I have the same issue as before but in a server. The problem I see here is that every time the app runs in MatrixDS it creates a new URL (subdomain), so I guess this solution won't work for me! 

Thanks for your help though and really glad I could make it run, at least locally! 

Cheers and congrats.

**Comment by dkulp2** [comment]
Yes, if your app has a different URL or changing IP address, then this won't work for you.

For what it's worth, I use a more traditional cloud hosting service (Google Cloud). I reserve an external IP for my app instance. (For an on-demand app - even just one instance - I create a Load Balancer and use that external IP instead.) I create a DNS A record for the external IP and put the DNS name in the OAuth.
